### ISSUE TITLE
Error in plot_profiles 'cluster_species' must match column names of profile matrix.

### ISSUE THREAD

**Issue by alexvasilikop** [almeidasilvaf/syntenet#9] opened 2022-10-13 16:55 UTC
Hello,

I performed the full pipeline up to plotting the profile but when I try to plot the profile,
I get the following error:
$plot_profiles(
     profiles, species_annotation, 
     cluster_species = species_order, 
     cluster_columns = TRUE

Error in plot_profiles(profiles, species_annotation, cluster_species = species_order,  : 
  'cluster_species' must match column names of profile matrix.

After checking the matrix, it seems that it is missing 2 species but these were initially included (9 in the matrix but 11 originally):
$head(profiles$profile_matrix)
      
 ->          ar av bc dc hm pl ps rc rr
 -> 8164  2  0  0  0  0  0  0  0  0
 -> 8163  2  0  0  0  0  0  0  0  0
 -> 8162  2  0  0  0  0  0  0  0  0
 -> 8161  2  0  0  0  0  0  0  0  0
 -> 8159  2  0  0  0  0  0  0  0  0
 -> 8158  2  0  0  0  0  0  0  0  0

What might be the issue?
Many thanks
Alex

**Comment by almeidasilvaf** [comment] 2022-10-13 17:18
Hi, @alexvasilikop 

It seems like the MCScanX algorithm (implemented in `syntenet`) could not detect any syntenic block for these 2 species.

Have you checked if they are present in the resulting synteny network? 

Suppose your network is in an object named `net`, the code below will give you a list of all species represented in the network:

```
# Get all genes in the synteny network
genes <- unique(c(net$Anchor1, net$Anchor2))

# Get species list (based on species abbreviations in front of gene IDs)
species <- unique(gsub("_", "", genes))
```

If you cannot see the missing species in the `species` object, it means `syntenet` did not find syntenic blocks in these 2 species. If that is your case, I'd guess:

- these 2 genomes are not very closely related to all the other species or;
- these 2 genomes have low quality (which you can assess, for instance, based on the percentage of complete BUSCOs)

Best,
Fabricio

**Comment by alexvasilikop** [comment] 2022-10-14 11:36
Hi Fabricio,

I think you are right the species were missing from this list. I tried relaxing the synteny parameters 
a lot in the synteny inference as follows and was able to recover one more species in the list
net <- infer_syntenet(blast_list, pdata$annotation, max_gaps = 80, anchors = 2)

Building a phylogenomic profile looks like this:
/home/alex/Desktop/new.pdf

I am interested in the phylogeny of the taxonomic groups but it seems there is not enough synteny for answering these questions (except within the first group?). What do you think? The tree inferred looks like this and removing the branch lengths you can see a tree-like pattern. I am not sure how much I can trust these results though..
/home/alex/Desktop/syntenet/tree.branch_lengths.pdf

/home/alex/Desktop/syntenet/tree.iqtree.no_branches.pdf

Thanks

**Comment by almeidasilvaf** [comment] 2022-10-14 12:05
Hi, @alexvasilikop 

Note that `syntenet::infer_microsynteny_phylogeny()` uses the "MK+FO+R" IQTREE2 model as default, but you can change it based on your preferences. 

As you don't have synteny clusters that are preserved throughout the whole phylogeny (a.k.a. "deeply conserved clusters"), it is usually recommended that you apply ascertainment bias correction (ASC, see more here: http://www.iqtree.org/doc/Tutorial, section **Binary, morphological and SNP data**).

Your call to `syntenet::infer_microsynteny_phylogeny()` would look something like this:

```
tree_files <- infer_microsynteny_phylogeny(transposed_matrix, model = "MK+ASC+R")
```

Then, you can see if your tree makes sense based on previous literature evidence. Let me know if that works. If your problems are solved, feel free to close the issue.

Best,
Fabricio

**Comment by alexvasilikop** [comment] 2022-10-17 12:22
Hi again,

I just checked now. It seems a bit strange that this one species is missing again from the synteny network. When I ran the pipeline as described here https://github.com/zhaotao1987/SynNet-Pipeline/wiki, 
the species was in included..

I am still looking into it
cheers

**Comment by almeidasilvaf** [comment] 2022-10-17 12:34
Hi, @alexvasilikop 

As this seems to be related to the data (and not with the package), I will close this issue, then. 

If you find any bug, feel free to open another issue here. If it's a general question (not a bug), please post it on the Bioconductor support site (https://support.bioconductor.org/) with the tag "#syntenet" on it and I'll be happy to answer.

Best,
Fabricio

**Closed by almeidasilvaf** 2022-10-17 12:34 UTC
