### ISSUE TITLE
check_input issue with number of genes 

### ISSUE THREAD

**Issue by aurelim** [almeidasilvaf/syntenet#19] opened 2023-11-29 09:01 UTC
Hi Fabricio,
Thanks for syntenet that i used with success previously. But i'm currently trying to use it with another dataset and I cannot pass the "check_input" step which tells me that I do not have the same number of genes in the annot and seq objects. But I don't understand why, since it seems that I have the same number of genes in both objects. I also checked that the genes had the same identifiers in both objects. However, the order of genes may differ. I'm using the 1.0.4 version of syntenet. 

```R
# Create annot and seq objects
annot_files <- dir(here("data", "gff_whole_haplotype"), full.names = TRUE)
annot <- lapply(annot_files, function(x) {
  granges <- rtracklayer::import(x, feature.type = "mRNA")
  ## Keep only useful fields
  granges <- granges[, c("source", "type","ID")]
  return(granges)
})

annot <- lapply(annot, function(x) {
  x$gene_id <- x$ID
  return(x)
})
names(annot)<- gsub(".gff3", "", basename(annot_files))
annot <- GenomicRanges::GRangesList(annot)


seq <- fasta2AAStringSetlist(here("data", "faa_whole_haplotype"))
names(seq) <- gsub(".faa", "", names(seq))

```

```R
GRangesList object of length 3:
$g1
GRanges object with 49762 ranges and 4 metadata columns:
          seqnames        ranges strand |   source     type             ID        gene_id
             <Rle>     <IRanges>  <Rle> | <factor> <factor>    <character>    <character>
      [1]    chr11   60034-62654      + |  Helixer     mRNA chr11_000001.1 chr11_000001.1
      [2]    chr11   70990-73157      + |  Helixer     mRNA chr11_000002.1 chr11_000002.1
      [3]    chr11 101227-102983      + |  Helixer     mRNA chr11_000003.1 chr11_000003.1
      [4]    chr11 110674-113051      + |  Helixer     mRNA chr11_000004.1 chr11_000004.1
      [5]    chr11 115581-116644      + |  Helixer     mRNA chr11_000005.1 chr11_000005.1
      ...      ...           ...    ... .      ...      ...            ...            ...
  [49758]    chr08 197167-197997      - |  Helixer     mRNA chr08_002377.1 chr08_002377.1
  [49759]    chr08 185223-185616      - |  Helixer     mRNA chr08_002378.1 chr08_002378.1
  [49760]    chr08 184933-185202      - |  Helixer     mRNA chr08_002379.1 chr08_002379.1
  [49761]    chr08   75215-78676      - |  Helixer     mRNA chr08_002380.1 chr08_002380.1
  [49762]    chr08    8161-13604      - |  Helixer     mRNA chr08_002381.1 chr08_002381.1
  -------
  seqinfo: 27 sequences from an unspecified genome; no seqlengths

$g2
GRanges object with 51889 ranges and 4 metadata columns:
          seqnames        ranges strand |   source     type             ID        gene_id
             <Rle>     <IRanges>  <Rle> | <factor> <factor>    <character>    <character>
      [1]     chr1 168478-173744      + |  Helixer     mRNA  chr1_000001.1  chr1_000001.1
      [2]     chr1 265069-265444      + |  Helixer     mRNA  chr1_000002.1  chr1_000002.1
      [3]     chr1 265600-268030      + |  Helixer     mRNA  chr1_000003.1  chr1_000003.1
      [4]     chr1 502438-508271      + |  Helixer     mRNA  chr1_000004.1  chr1_000004.1
      [5]     chr1 509859-511858      + |  Helixer     mRNA  chr1_000005.1  chr1_000005.1
      ...      ...           ...    ... .      ...      ...            ...            ...
  [51885]    chr17   97801-99401      - |  Helixer     mRNA chr17_002946.1 chr17_002946.1
  [51886]    chr17   87252-88373      - |  Helixer     mRNA chr17_002947.1 chr17_002947.1
  [51887]    chr17   81823-84434      - |  Helixer     mRNA chr17_002948.1 chr17_002948.1
  [51888]    chr17   76884-81270      - |  Helixer     mRNA chr17_002949.1 chr17_002949.1
  [51889]    chr17    9506-28460      - |  Helixer     mRNA chr17_002950.1 chr17_002950.1
  -------
  seqinfo: 27 sequences from an unspecified genome; no seqlengths

$g3
GRanges object with 45344 ranges and 4 metadata columns:
          seqnames        ranges strand |   source     type             ID        gene_id
             <Rle>     <IRanges>  <Rle> | <factor> <factor>    <character>    <character>
      [1]     chr1   28284-32837      + |  Helixer     mRNA  chr1_000001.1  chr1_000001.1
      [2]     chr1   32839-33270      + |  Helixer     mRNA  chr1_000002.1  chr1_000002.1
      [3]     chr1   41122-41853      + |  Helixer     mRNA  chr1_000003.1  chr1_000003.1
      [4]     chr1 201883-205824      + |  Helixer     mRNA  chr1_000004.1  chr1_000004.1
      [5]     chr1 285846-287931      + |  Helixer     mRNA  chr1_000005.1  chr1_000005.1
      ...      ...           ...    ... .      ...      ...            ...            ...
  [45340]    chr17   62188-63727      - |  Helixer     mRNA chr17_002687.1 chr17_002687.1
  [45341]    chr17   51453-52580      - |  Helixer     mRNA chr17_002688.1 chr17_002688.1
  [45342]    chr17   46003-48489      - |  Helixer     mRNA chr17_002689.1 chr17_002689.1
  [45343]    chr17   41160-44467      - |  Helixer     mRNA chr17_002690.1 chr17_002690.1
  [45344]    chr17    7668-14019      - |  Helixer     mRNA chr17_002691.1 chr17_002691.1
  -------
  seqinfo: 27 sequences from an unspecified genome; no seqlengths

```

```R
$g1
AAStringSet object of length 49762:
        width seq                                                                              names               
    [1]  1580 MNEPRICHTLMTPNGNLHPKPNERKFPTLMVSQYLHSKN...IDYLGKLIWNYCILDEGHVIKNAKSKVTLSVKQLKAQH chr11_003021.1
    [2]    55 MIYYGPAVLSSPPPSHSLGHWFNPSDEIYGCSADRGHCQSASSGLELSVENALKM                          chr11_003020.1
    [3]   321 MLVITVDYLKKRVISLNNLVEIYCVHHPKHLLDYAALMS...GAVGVMKTGDFKRIHRTTRRISLTCRLVSKVHKNLLRF chr11_003019.1
    [4]   552 MSGMMLMLLLCLSVGTMSVVHCGDPTIFFTWNVTYGTLS...YVGVENIKRSLRNEYNMPDTALVCGLVKGMPKPPPYST chr11_000001.1
    [5]   552 MASVMYALLLCLSAGALSMVQGEDPYLFFTWNVTYGTIS...YVSVLSPARSLRDEYNLPETAQLCGIVKDLPKPPPYSS chr11_000002.1
    ...   ... ...
[49758]   227 MEAQEVEAQAATGSGQQQLKLYSYWMSSCSFRVRIALNL...RFQLDMTQFPLLARLHEAYNKIPAFLDALPEKQPDAPS chr08_001162.1
[49759]    76 MVLTKMKEIAESYLGQMVKNIVLTVPAYFNDSQQQATKDAGAISGLNVMRIINEPMAAAIAYGLDKKASRKGSRTS     chr08_001161.1
[49760]   742 MDNKQPLLLSQGSGGHVNYYVNLRKTSLSVTFAKWILKI...VCGPPTLQSSVAKEIRSHNLRRQFDHPIFHFNSHSFDL chr08_001158.1
[49761]   581 MSMYGRDPWGGPLEINTADSATDDDRSRNLQDLDRAALS...ALVALSGEKSVGIDKNTIFSAVPPMFPTPPPPPAPWKP chr08_001159.1
[49762]   411 MGGCTCLLCHYSALFVPSVLFINSERHEEQDALFEALHK...NVQQYIGSWVGGAKGKQDKTDSDQSLSQRIPIDIVISN chr08_001160.1

$g2
AAStringSet object of length 51889:
        width seq                                                                              names               
    [1]   221 MALSEATSVVPLNPETPSTNHAHSDQGSLPSSPDPDPTP...PVRPEAEDCSYYLKTGSCKFGSNCKFNHPVSRKTNQEI chr1_000001.1
    [2]    85 MELMKAKGGGGRLRHQQGRRLWEGSRGKKVMGGADEKGL...WDSPVVGCKEMLGLIGECVLEEYEEAQSSDDESFAIRR chr1_000002.1
    [3]   477 MVMGSSSRQSSGSNSRRVRAFKRWMKQEGIECSDALDLR...KLYHSLVLRISERKILRKLQIYAANAKEASWTNKLKRK chr1_000003.1
    [4]   757 MMNEENGSSSSSSSSLVSDDGGDIENLDLLDGRRRTCSQ...VETMSLAKAAILFRQLGLRHLCLVPKSQGGHKFPWNLG chr1_002382.1
    [5]    82 MIVHHLLPSHPSNHPSKPVACASASTTFEVDQAPTPATP...FQVGHEFDLHKLEPRYPLIISDIDIAQDRGWAAHSNVS chr1_002381.1
    ...   ... ...
[51885]   275 ERRLALEEVKFLQKQRERKSGIPALTNNNAATQTLPGST...VSRQNDTGTEAAGQRQAATDQFMLERFRKRERHRVMRR chr17_001458.1
[51886]   255 MTMASQSQSLQFFHSHIIIRRSTLPPPSLPFHFQLQLQL...VIEGMDVLRKLESQETSRLDVPRLPCRIVNCGELLLDD chr17_001454.1
[51887]   125 MSVLHIQYSQWPNQGVPEDTFSVREIEKRVMYQVAPAIP...QRDGMVQKPEQYRLCYDALVDELEDHISDGSPVEYLVK chr17_001457.1
[51888]    39 MSGPGTLWGSAESGNPTSRLGCVSRLSLLMVGLYFKDLA                                          chr17_001456.1
[51889]   838 MEVDTRQYLRDDQTSNCRSFGSINHPSSQSRKISIGVVV...TQINDAQRKIQVTRRMARGKMLQLKHELALCLKDGILS chr17_001455.1

$g3
AAStringSet object of length 45344:
        width seq                                                                              names               
    [1]    98 MLTSRTIPDSVHTVSRASGGHESSRRVKSELLVQVDGVN...EAFRRRLEKRLYIPLPNFQSRKALIRINMKPVEMWPLT chr1_000001.1
    [2]    45 MSKDDISKDPVAMCDFEEALAKVQRSVSQADIERHEKWIHEFGSA                                    chr1_000002.1
    [3]   224 MSGPSDRRFDLNLGEETATPSPDNIWRPSFISPTGPLTV...MPPPSGVLSSTEAPDNHPPVLSLSGALPTAETSPKQPL chr1_000003.1
    [4]   221 MALSEATSVVPPNPETPSTNHAHSDQGSLPSSPDPDPTP...PVRPEAEDCSYYLKTGSCKFGSNCKFNHPVSRKTNQEI chr1_000004.1
    [5]   480 MKQEGIECSDALDLRNDGATAGGVGISVRAVGDLKEGDV...KLYHSLVLRISERKILRKLQIYAANAKEASWTNKLKRK chr1_000005.1
    ...   ... ...
[45340]   125 MSVLHIQYSQWPNQGVPEDTFSVREIEKRVMYQVAPAIP...QRDGMVQKPEQYRLCYDALVDELEDHISDGSPVEYLVK chr17_001338.1
[45341]    43 MSGPGTLWGSAESGNPTSRLGCVSRLSLLMIRGWALLQRPCLI                                      chr17_001337.1
[45342]   808 MEVDTRQYLRDDQTSNCRSFGSINHPSSQSRKISIGVVV...TQINDAQRKIQVTRRMARGKMLQLKHELALCLKDGILS chr17_001336.1
[45343]   322 MACLHLPDLVTHNIIQILPTKAAVRMSFLSKQWEGVWCS...HDESYKKAEIYKGKNKVLNGSPILRQKIQPIQRGCIQI chr17_001334.1
[45344]   954 MPSVWFSISGAFSLCCTVITEFSAALQRVGDFDHASYTP...FVGQPSPVTPRPSEQLAGTEGLPSFHSPKQGRKYRKYR chr17_001335.1
```
```R
Erreur dans check_ngenes(seq, annotation) : 
  Number of sequences in greater than the number of genes for:
1. g1
2. g2
3. g3
```
Thank you for your help,
Best,
Aurelie

**Comment by almeidasilvaf** [comment] 2023-11-29 11:09
Hi, @aurelim 

The problem is that you created the GRanges objects from the GFF files using `feature.type = "mRNA"`.

```r
granges <- rtracklayer::import(x, feature.type = "mRNA")
```

When you do that, all rows will have "mRNA" in the column `type`, but __syntenet__ expects them to be "gene" (since you're working with genes). In other words, by having no "gene" ranges, __syntenet__ understands that you have no genes whatsoever.

What you could is:
1. Read the GFF files as GRanges without the `feature.type = "mRNA"` argument,
2. Rename the observations in column type to "gene", even though they are mRNAs.

Best,
Fabricio

**Comment by aurelim** [comment] 2023-11-29 13:00
Thank you for responding so quickly, problem solved !

**Comment by almeidasilvaf** [comment] 2023-11-29 17:19
Glad to know it is solved! :tada: 

I will close the issue, then.

**Closed as completed by almeidasilvaf** 2023-11-29 17:19 UTC
